"""Update Category model.

Revision ID: c4d363e32c6a
Revises: ed5e1e1c619d
Create Date: 2025-03-06 16:17:07.201841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d363e32c6a'
down_revision = 'ed5e1e1c619d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
